version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
